# Generated by Django 5.2.13 on 2026-09-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ycms", "0085_blog_date_editable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anyfile",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="anyfile",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="button",
            name="hover_text_en",
        ),
        migrations.RemoveField(
            model_name="button",
            name="text_en",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_en",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_en",
        ),
        migrations.RemoveField(
            model_name="fileentry",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="galerie",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="galerie",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="galeryimage",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="pricingcard",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="pricingcard",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="pricingfeature",
            name="text_en",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="vacationText_en",
        ),
        migrations.RemoveField(
            model_name="videofile",
            name="alt_text_en",
        ),
        migrations.RemoveField(
            model_name="videofile",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="videofile",
            name="place_en",
        ),
        migrations.RemoveField(
            model_name="videofile",
            name="tags_en",
        ),
        migrations.RemoveField(
            model_name="videofile",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="vacationText_en",
        ),
    ]
