# Generated by Django 5.2.13 on 2026-08-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_rename_shop_to_immobilien_labels"),
        ("shop", "0008_strip_language_suffix_from_product_slugs"),
    ]

    operations = []
