# Generated by Django 5.2.13 on 2026-09-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_free_address_and_coordinates"),
        ("ycms", "0086_remove_anyfile_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="position_manual",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Position von Hand gesetzt"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_image_alt",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Alt-Text Titelbild",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_image_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Bildtitel Titelbild",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="objects_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ycms.anyfile",
                verbose_name="Objektliste (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="objects_document_title",
            field=models.CharField(
                blank=True, default="Unsere Objekte", max_length=120
            ),
        ),
    ]
