# Generated by Django 5.2.13 on 2026-09-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_image_meta_manual_position_objects_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('latitude', models.FloatField(blank=True, editable=False, null=True)),
                ('longitude', models.FloatField(blank=True, editable=False, null=True)),
                ('position_manual', models.BooleanField(default=False, editable=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_addresses', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'address'), name='unique_product_address')],
            },
        ),
    ]
